# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7088f6b0299292e74714c3018e982556a09bd3bddda828295d712a4824d5b22e8e2ada2e960626ad1a8aef9f6a443fd9535c666bbc51de90c84a62ab1b6c57b2

test:
  secret_key_base: 20a99edfeb0bf8e7220f289dc95399e0ff5fac87e3b0ff2fd29f43359c386454b3bf0e438afdc6ce789929d05f38b222cb69b6046f548e3207012b2dc6588537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
